### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by cchantep** [zengularity/query-monad-example#1]
At least to check everything compile (Travis? Circle?)

**Comment by stankoua** [comment]
Yes, I'm willing to add one but I'm not familiar with CI tools. Which one do you recommend?

**Comment by cchantep** [comment]
https://github.com/cchantep/alohura/blob/master/.travis.yml

**Comment by stankoua** [comment]
Like the link you shared above, I set up a configuration file for Travis CI and a script for validation.
Please take a look at PR #9  ;-)
